// File:   docs.script
// Author: Robert L Walton <walton@acm.org>
// Date:   Mon Jan 29 03:39:57 EST 2024
// 
// The authors have placed RECKON (its files and the
// content of these files) in the public domain; they
// make no warranty and accept no liability for RECKON.

const docs_list = [
    ['h2','Reference'],
    ['reckon_lexemes.html','RECKON Lexemes'],
    ['h2','Maintenance'],
    ['web_page_maintenance.html','Web Page Maintenance']
];
